version: 2
updates:
  - package-ecosystem: gomod
    directory: "/services/identity-service"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/services/creator-service"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/services/stream-service"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
