CREATE TABLE metric_aggregates (
    metric_name VARCHAR(255) NOT NULL,
    time_bucket TIMESTAMPTZ NOT NULL,
    dimensions JSONB NOT NULL DEFAULT '{}',
    count BIGINT NOT NULL DEFAULT 0,
    sum DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg DOUBLE PRECISION NOT NULL DEFAULT 0,
    p50 DOUBLE PRECISION NOT NULL DEFAULT 0,
    p95 DOUBLE PRECISION NOT NULL DEFAULT 0,
    p99 DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (metric_name, time_bucket)
);
